parameters:
  - name: path
    type: string
  - name: project
    type: string
  - name: job
    type: string

stages:
- stage: JobDeploy
  jobs:
  - job: main
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '${{ parameters.path }}/${{ parameters.project }}/${{ parameters.project }}.csproj'
        arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/WebJob/App_Data/jobs/triggered/${{ parameters.job }}'

    - script: 'echo "dotnet ${{ parameters.project }}.dll" > run.cmd'
      workingDirectory: '$(Build.ArtifactStagingDirectory)/WebJob/App_Data/jobs/triggered/${{ parameters.job }}'
      displayName: 'Command Line Script'

    - task: FtpUpload@2
      displayName: 'FTP Upload: $(Build.ArtifactStagingDirectory)/WebJob'
      inputs:
        serverEndpoint: 'BASTARun'
        rootDirectory: '$(Build.ArtifactStagingDirectory)/WebJob'
        remoteDirectory: /site/wwwroot
        preservePaths: true
        trustSSL: true
